server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-ct0oms56l47c73b7lle0-a.oregon-postgres.render.com:5432/projeto_java_user
        username: projeto_java_user
        password: YYIKxCwG62XgkAGxoKSj55RABk9udSMG
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
